version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - hugomrdias
  labels:
  - topic/dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: esbuild
    versions:
    - 0.10.0
    - 0.10.1
    - 0.11.0
    - 0.11.10
    - 0.11.11
    - 0.11.12
    - 0.11.13
    - 0.11.15
    - 0.11.2
    - 0.11.3
    - 0.11.5
    - 0.11.6
    - 0.11.9
    - 0.9.0
    - 0.9.1
    - 0.9.3
    - 0.9.4
    - 0.9.6
  - dependency-name: electron
    versions:
    - 12.0.0
    - 12.0.1
    - 12.0.2
  - dependency-name: typescript
    versions:
    - 4.2.2
    - 4.2.3
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: "@commitlint/load"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/travis-cli"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/lint"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/read"
    versions:
    - 12.0.0
  - dependency-name: eslint-config-ipfs
    versions:
    - 2.0.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: terser-webpack-plugin
    versions:
    - 4.2.3
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: webpack-merge
    versions:
    - 5.7.3
