language: node_js
cache: npm
stages:
  - check
  - test
  - cov

node_js:
  - '10'
  - '12'

os:
  - linux
  - osx

script: npx nyc -s npm run test:node -- --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - os: windows
      cache: false

    - stage: check
      script:
        - node cli.js commitlint --travis
        - node cli.js dep-check -- -i aegir
        - npm run lint

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npm run test:browser

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npm run test:browser -- -- --browsers FirefoxHeadless

notifications:
  email: false